market:
 image: node
 links:
  - rabbitmq
  - redis
  
rabbitmq:
 image: rabbitmq
 ports:
  - "4369:4369"
  - "5671:5671"
  - "5672:5672"
  - "25672:25672"
 
redis:
 image: redis
 ports:
  - "6379:6379"